/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import org.junit.Test;
import static org.junit.Assert.*;

public class ShellSort {
    @Test
    public void testShellSort() {
        Integer[] given = new Integer[] { 0, 8, 6, 4, 1, 3, 2, 5, 7, 9 };
        Integer[] expected = new Integer[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
        Sort.shell(given);
        assertArrayEquals("Sorting Failed! ", expected, given);
    }
}
