/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Sort<Integer> sort = new Sort<>();

        Integer[] data = new Integer[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };

        sort.shell(data);

    }
}
